### ISSUE TITLE
Coverage backup

### ISSUE THREAD

**Issue by robertdstein** [desy-multimessenger/nuztf#217]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try drafting a gcn, but discover the ZTF log is broken.

**Describe the solution you'd like**
Since a consistent method to access the log does not seem to work, I propose a manual bypass where you can add the field in manually.

**Describe alternatives you've considered**
Repeatedly complaining until skyvision becomes 100% reliable.

**Comment by simeonreusch** [comment]
I implemented html page parsing as fallback in `ztfquery.skyvision` (yields the same results, differing only slightly in `obsmjd`). This solves the issue.
