### ISSUE TITLE
Dedicated emgw ampel fritz group

### ISSUE THREAD

**Issue by robertdstein** [desy-multimessenger/nuztf#302]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when we push Ampel crap into the main emgw group. We just need to make a dedicated Fritz group instead, and point the Skymap Scanner to this group. We can then share candidates as needed.

**Comment by robertdstein** [comment]
Yes it's easy, I just need to make a group on Fritz and change the default group number in nuztf. This is more to ensure I remember :)

**Comment by simeonreusch** [comment]
Note to myself: Use different default `group_id` depending on the event type

**Comment by robertdstein** [comment]
Done

**Comment by robertdstein** [comment]
For posterity:

https://github.com/desy-multimessenger/nuztf/blob/a5b8c20e00c48c1c9a8289498a61b4e537107087/nuztf/skymap_scanner.py#L35
