### ISSUE TITLE
Cache crossmatch

### ISSUE THREAD

**Issue by robertdstein** [desy-multimessenger/nuztf#305]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the nuztf analysi takes forever. I blame slow catalog crossmatching.

**Describe the solution you'd like**
We should cache by ZTF name. The result will always be the same, so no need to repeat. Could also cache thumbnails or whatever else is slow to download.

**Comment by simeonreusch** [comment]
Fixed with #306
