### ISSUE TITLE
BUG? Test compatibility with new ZTF alerts

### ISSUE THREAD

**Issue by robertdstein** [desy-multimessenger/nuztf#39]
**Describe the bug**
ZTF alerts will swap from previous detection history to forced photometry history. This might break things, we need to check. The changeover will be in 1 month, and we may have 1 week to play with example data beforehand.

**Expected behavior**
Ideally backwards compatibility should be maintained (i.e the pipeline still works in the same way for old alerts), but the pipeline will also need to be compatible with new alerts. I have no idea how much of an issue this will be, perhaps ampel will take care of everything. It needs to be checked though.

**Additional context**
Co-ordinating with Jakob Nordin and Jakob van Santen is advised.

**Comment by JannisNe** [comment]
Update: new ZTF alerts will be rolled out in December.

**Comment by JannisNe** [comment]
Test sample alerts using the `ampel alert shaper`

**Comment by JannisNe** [comment]
All this is being worked on in the branch `avro_package_update`
