### ISSUE TITLE
Clean up code / Purge legacy functionality

### ISSUE THREAD

**Issue by simeonreusch** [desy-multimessenger/nuztf#4]
**Is your feature request related to a problem? Please describe.**
Everything is contained in ampel_magic.py. Maybe compartmentalize this more? Would make bug-fixing easier and improve readability.

**Describe the solution you'd like**
Split ampel_magic.py to functional sub-units.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by robertdstein** [comment]
Can I also add that the code structure is rather messy. We should have one simple package name, and put all scripts except setup.py in that directory. Then you do the standard import method `from X.ampel_magic import...`

**Comment by simeonreusch** [comment]
A decent amount of cleanup has happened, will close this for now.
