### ISSUE TITLE
Use CI with Ampel

### ISSUE THREAD

**Issue by robertdstein** [desy-multimessenger/nuztf#5]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when an alert comes in, so we trigger ToO and then try to use the pipeline only to discover that, of course, everything is broken.

**Describe the solution you'd like**
Set up proper CI for the pipeline code. We can use github actions, to trigger on every commit. We could also perhaps use Travis CI. We need a secret/secure way of accessing the private ampel repos, but I think that can be done. We can also set it to trigger periodically, e.g monthly/weekly, to check updates in dependencies. Making unit tests would be ideal, but in the interim using something like https://github.com/robertdstein/at2019dsg/blob/master/.travis.yml to run the ipython notebooks and check for errors would provide decent code coverage.

**Describe alternatives you've considered**
Leaving things as they are.

**Comment by robertdstein** [comment]
Assuming that #2 is done, we could also set up automated deployment to Pypi

**Comment by robertdstein** [comment]
I am forseeing that setting up the ssh tunnels will also be a mess, but still potentially solveable.

**Comment by robertdstein** [comment]
Inspired by recent work on [flarestack](https://github.com/icecube/flarestack), I would suggest we could start using dependabot to maintain stable releases with fixed software versions

**Comment by robertdstein** [comment]
what is our dependency on `ampel-contrib-ztfbh`? could it be dropped? That is the only repo I am sure will not be open source.

**Comment by simeonreusch** [comment]
I just did `grep -r "ztfbh" . ` and it gave me no hits; so I assume we can drop this

**Comment by robertdstein** [comment]
More thoughts on potential problems: use of passwords. Workaround: give them as secret environment variables and use a script to create the necessary password files. I am specifically thinking of ztfquery passwords here.

**Comment by JannisNe** [comment]
As I did not reference the various commits, the status is that CI is set up but currently failing because ampel-contrib-HU is private.
todo:
* deal with ampel-contrib-HU being private (preferably make it public)
* implement unittests 
* use coveralls to test code coverage and identify unused parts of the code

**Comment by JannisNe** [comment]
As of [now](https://github.com/desy-multimessenger/ampel_followup_pipeline/commit/a38a694d9c81937cc6600120fe9edaa02ce9ff6d) there is a CI pipeline. Runs on pushes and also twice a month.

**Comment by robertdstein** [comment]
I think we need to modify dependabot a bit to enable it to access github secrets when opening a pull request. Related to: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544

**Comment by JannisNe** [comment]
I will look into it. It is weird that there would not be an error when the secret is not available to this job...

**Comment by robertdstein** [comment]
The way the code works though, it checks if the environment variable is available, and then sets up the `ztfquery` credentials. If the env variables are not set, the `ztfquery` credentials are not set, but that does not raise an error since it is optional. I think that is what generated an error for #11 .

**Comment by JannisNe** [comment]
I was more talking about the pipeline giving an error. I would have suspected that when it tries to access the secret but cannot do that that it would give an error.

**Comment by robertdstein** [comment]
It is a good point to raise. My philosophy was that it is not needed because people might prefer to store passwords locally rather than in e.g a bash file, but then it can lead to mysterious `ztfquery` errors which are hard to decipher. Perhaps we should just modify `credentials.py` to raise errors if the login details are not exported, and modify the `readme.md` accordingly. I am happy to go with a democratic decision here.

**Comment by robertdstein** [comment]
Apparently you can manually rerun each pull request, and in that case all the secrets are correctly passed. That's an interim solution, though it feels suboptimal.
