### ISSUE TITLE
Local folder gets created in environment when scanning

### ISSUE THREAD

**Issue by SWeimann93** [desy-multimessenger/nuztf#75]
**Describe the bug**
While scanning pixels, local folder in env gets created, which shouldn't

**To Reproduce**
1. Run latest nuztf pipeline
2. While scanning pixels, error occours: No such file or directory: '.../anaconda3/envs/ZTF_TOO/lib/python3.8/site-packages/Neutrino_candidates/IceCube-210922A.pdf'

**Expected behavior**
Code should not create a folder in local environment

**Comment by JannisNe** [comment]
idea: use the `ztfquery` default

**Comment by simeonreusch** [comment]
Used Jannis' idea when rewriting basescanner and neutrino_scanner
