### ISSUE TITLE
Dependabot can not access repo secrets

### ISSUE THREAD

**Issue by JannisNe** [desy-multimessenger/nuztf#78]
**Describe the bug**
Dependabot needs to access Repo secrets to run CI.

**To Reproduce**
See the CI runs for a dependabot pull request.

**Expected behavior**
Dependabot pull requests do not crash.

**Comment by robertdstein** [comment]
Fixed. There was a whole extra secret SECRETS place for dependabot! It should work from now on, but we need to remember to update secrets in both places going forward.
